USE ca_db;

CREATE TABLE IF NOT EXISTS `user` (
`user_id` INT AUTO_INCREMENT NOT NULL,
`token` VARCHAR(255) NOT NULL,
`name` VARCHAR(8) NOT NULL,
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`user_id`));